version: '3'
services: 
    course-service:
        build: ./course-service
        volumes: 
            - ./course-service:/usr/src/app
        ports: 
            - 3000:8080
    website:
        image: nginx:alpine
        volumes: 
            - ./website:/usr/share/nginx/html
        ports: 
            - 3001:80
        depends_on: 
            - course-service
